version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: coin-trackr-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: coin-tracker-pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coin-trackr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d coin-tracker-pg"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coin-trackr-backend
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: dev
      PORT: 3333
      DATABASE_URL: postgresql://docker:docker@postgres:5432/coin-tracker-pg?schema=public
      JWT_SECRET: ${JWT_SECRET}
      COINGECKO_API_KEY: ${COINGECKO_API_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      CRON_ENABLED: ${CRON_ENABLED:-true}
      CRON_SCHEDULE: ${CRON_SCHEDULE:-*/5 * * * *}
      CRON_TIMEZONE: ${CRON_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - coin-trackr-network
    command: npm run start:dev

  # Redis (Optional - for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: coin-trackr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coin-trackr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  coin-trackr-network:
    driver: bridge